default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_development" %>
  cache:
    <<: *default
    database: storage/<%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_cache_development" %>
    migrations_path: db/cache_migrate
  cable:
    <<: *default
    database: storage/<%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_cable_development" %>
    migrations_path: db/cable_migrate
test:
  <<: *default
  database: <%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_test" %>

production:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", 'url_production_database') %>
  cache:
    <<: *default
    database: storage/<%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_cache_production" %>
    migrations_path: db/cache_migrate
  cable:
    <<: *default
    database: storage/<%= "#{ENV.fetch('APPLICATION_NAME', 'app')}_cable_production" %>
    migrations_path: db/cable_migrate
